[package]
name = "wgdiff"
description = "Implementation of LCS-based diff algorithm"
readme = "README.md"
repository = "https://github.com/Daniikk1012/wgdiff-rs"
version = "0.3.0"
edition = "2021"
license = "MPL-2.0"

[dev-dependencies]
rand = { version = "0.8", features = ["small_rng"] }
