[package]
name = "wgdiff"
description = "Implementation of LCS-based diff algorithm"
readme = "README.md"
repository = "https://github.com/Daniikk1012/wgdiff-rs"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
license-file = "LICENSE"
